### PyTorch

- numpy가 지원하는 연산들을 GPU에서 할 수 있도록 함
- 높은 성능과 유연성을 제공하는 딥러닝 지원

> 따라서, numpy와 유사한 기능이 많음

**pytorch 일반적인 import 형태**

In [2]:
import torch

**Tensor 생성**

- Tensor는 numpy의 ndarray와 유사한 구조를 지님

**scala (0D 텐서)**

- scala 로 numpy 만들 수 있습니다.

In [4]:
import numpy as np

data1 = np.array(10)
print(data1, data1.ndim, data1.shape) # ndim은 axis축, shape은 행렬의 차원을 의미함

10 0 ()


**vector (1D 텐서)**

- vector부터는 pytorch의 tensor로 만들 수 있음
- shape은 torch.Size([3])과 같이 표현됩니다.

In [14]:
import torch

data1 = torch.FloatTensor([1,2]) # 1,2 원소를 가진 1D 텐서를 선언
print(data1, data1.ndim, data1.shape)

data2 = torch.FloatTensor(3)
print(data2, data2.ndim, data2.shape)

tensor([1., 2.]) 1 torch.Size([2])
tensor([0., 0., 0.]) 1 torch.Size([3])


In [17]:
# matrix (2D 텐서)

data3 = torch.FloatTensor(3,2)
print(data3, data3.ndim, data3.shape)

data4 = torch.FloatTensor([[1,2],[3,4],[5,6]])
print(data4, data4.ndim, data4.shape)


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) 2 torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 2 torch.Size([3, 2])


In [23]:
# 3D 텐서

data5 = torch.FloatTensor(3,2,1)
print(data5, data5.ndim, data5.shape)

data6 = torch.FloatTensor([[[1],[2]],[[3],[4]],[[5],[6]]])
print(data6, data6.ndim, data6.shape)


tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]) 3 torch.Size([3, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]]) 3 torch.Size([3, 2, 1])


In [26]:
# 밖에서부터 안쪽으로 텐서 선언의 이해
data7 = torch.FloatTensor([[1],[2],[3]])
print(data7, data7.ndim, data7.shape)

data8 = torch.FloatTensor([[1,2,3]])
print(data8, data8.ndim, data8.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([[1., 2., 3.]]) 2 torch.Size([1, 3])


In [37]:
data1 = torch.zeros(3, dtype=torch.float)
print(data1)
data2 = torch.ones(2,2, dtype=torch.double)
print(data2)
data3 = torch.rand(2,2,3, dtype=torch.half)
print(data3)
data4 = torch.randn(2,2,3,4)
print(data4)
data5 = torch.full((2,4), 10)
print(data5)

tensor([0., 0., 0.])
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[[0.5137, 0.7686, 0.8335],
         [0.3950, 0.3086, 0.7261]],

        [[0.0479, 0.6274, 0.7832],
         [0.5850, 0.1909, 0.8901]]], dtype=torch.float16)
tensor([[[[ 0.0811,  0.3062, -1.2355, -1.1281],
          [-0.5444, -1.1448, -0.6339,  0.5816],
          [-0.0259, -0.1619,  0.1930,  0.9442]],

         [[-1.2119, -1.8076, -0.8704,  0.8878],
          [-0.9709,  0.1472,  1.3055, -1.4564],
          [-0.8289,  1.1651,  0.2112,  0.9574]]],


        [[[-1.1322, -0.0762,  1.2864,  1.1212],
          [-0.9547,  0.6378, -0.6512, -0.2183],
          [ 0.4214, -1.0205, -1.5117, -0.8665]],

         [[ 0.4093,  1.1126,  0.4348,  0.4117],
          [ 1.8167, -0.2309, -0.2957,  0.6260],
          [-0.4418,  1.1247, -0.4216,  0.2126]]]])
tensor([[10, 10, 10, 10],
        [10, 10, 10, 10]])


In [40]:
# 형태 확인
print(data1.shape, data2.shape, data3.shape, data4.shape, data5.shape)

torch.Size([3]) torch.Size([2, 2]) torch.Size([2, 2, 3]) torch.Size([2, 2, 3, 4]) torch.Size([2, 4])


In [43]:
# 배열의 차원을 나타냄
print(data1.ndim, data2.ndim, data3.ndim, data4.ndim, data5.ndim)

1 2 3 4 2


In [44]:
print(data1.dtype, data2.dtype, data3.dtype, data4.dtype, data5.dtype)

torch.float32 torch.float64 torch.float16 torch.float32 torch.int64


In [47]:
# 데이터 사이즈(원소 갯수) 확인
# numpy와 달리 size가 아닌 size() 메서드 제공
print(data1.size(), data2.size(), data3.size(), data4.size(), data5.size())

torch.Size([3]) torch.Size([2, 2]) torch.Size([2, 2, 3]) torch.Size([2, 2, 3, 4]) torch.Size([2, 4])


In [53]:
data6 = torch.FloatTensor([[1,2],[3,4]])
data7 = torch.DoubleTensor([[1,2,3],[4,5,6]])
data8 = torch.LongTensor([[1,2,3],[4,5,6],[7,8,9]])

data9 = torch.FloatTensor(2,3,5)
data10 = torch.DoubleTensor(3,3,2,4)
data11 = torch.LongTensor(4,4)
print(data11)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [50]:
# _like()로 텐서 생성
data12 = torch.full_like(data5, 20)

print(data5)
print(data12)

tensor([[10, 10, 10, 10],
        [10, 10, 10, 10]])
tensor([[20, 20, 20, 20],
        [20, 20, 20, 20]])


**reshape() : 배열 구조 변경**

In [62]:
import torch

data1 = torch.DoubleTensor([[1,2,3],[4,5,6]])
print(data1, data1.size(), data1.shape)

data1 = data1.reshape(3,2)
print(data1, data1.shape)

data1 = data1.reshape(1,-1) # -1은 열을 행의 갯수에 맞춰 자동 계산
print(data1, data1.shape)


tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) torch.Size([2, 3]) torch.Size([2, 3])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64) torch.Size([3, 2])
tensor([[1., 2., 3., 4., 5., 6.]], dtype=torch.float64) torch.Size([1, 6])


**view() : 텐서 구조 변경**

- pytorch에서는 numpy처럼 reshape()로 배열 구조를 변경할 수 있지만, reshape() 보다는 view()메서드를 보다 많이 사용함
- view()메서드는 reshape()랑 사용법 동일

> 원소 수를 유지하면서 텐서의 크기를 변경할 때 많이 사용하며, 매우 중요함!

In [67]:
import torch

data1 = torch.DoubleTensor([
    [[1,2,3],
    [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])

print(data1.shape, "높이(k) : ",data1.size(0), "너비(n) : ",data1.size(1), "깊이(m) : ",data1.size(2))

torch.Size([2, 2, 3]) 높이(k) :  2 너비(n) :  2 깊이(m) :  3


In [77]:
data1 = data1.view(2,-1) # (2,?) 으로 구성, -1은 자동 계산
print(data1, data1.shape)

data1 = data1.view(-1,3) # (?,3) 으로 구성
print(data1, data1.shape)

data1 = data1.view(3,2,-1) # (3,2,?) 으로 구성
print(data1, data1.shape)


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]], dtype=torch.float64) torch.Size([2, 6])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64) torch.Size([4, 3])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]], dtype=torch.float64) torch.Size([3, 2, 2])


**squeeze() : 텐서 차원 압축**

- 차원이 1인 경우, 해당 차원을 제거

In [ ]:
data1 = torch.FloatTensor([[1],[2],[3]])
data2 = data1.squeeze()
print(data1, data1.ndim, data1.shape)
print(data2, data2.ndim, data2.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([1., 2., 3.]) 1 torch.Size([3])


In [85]:
data4 = torch.randn(2,1,3,4)
data4 = data4.squeeze()
print(data4, data4.ndim, data4.shape)

tensor([[[-0.8045,  0.3882, -0.7459, -0.4086],
         [ 0.3001,  0.3762, -2.1080,  0.5432],
         [ 0.2749, -2.0034,  0.6125, -0.3785]],

        [[ 0.6988,  0.2892, -0.1220, -1.2459],
         [-0.3011,  0.2599,  0.1605, -1.2743],
         [ 0.1872, -0.4739, -0.6712,  0.2860]]]) 3 torch.Size([2, 3, 4])


**unsqueeze() : 특정 위치에 1인 차원을 추가**

In [86]:
data1 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(data1, data1.ndim, data1.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) 2 torch.Size([2, 3])


In [88]:
data2 = data1.unsqueeze(0)
data3 = data1.unsqueeze(2)

print(data2, data2.ndim, data2.shape)
print(data3, data3.ndim, data3.shape)

tensor([[[1., 2., 3.],
         [4., 5., 6.]]]) 3 torch.Size([1, 2, 3])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]]) 3 torch.Size([2, 3, 1])


**데이터 타입 변환(type)**

In [ ]:
data1 = torch.zeros(3, dtype=torch.float)
print(data1.dtype)
data2 = torch.ones(2,4, dtype=torch.double)
print(data2.dtype)
data3 = torch.rand(2,2,3, dtype=torch.half)
print(data3.dtype)

data1 = data1.type(dtype=torch.float32)
data2 = data2.type(dtype=torch.int)
data3 = data3.type(dtype=torch.double)

print(data1.dtype)
print(data2.dtype)
print(data3.dtype)

torch.float32
torch.float64
torch.float16
torch.float32
torch.int32
torch.float64


**T: 전치(transpose) 행렬**
- 행과 열을 교환하여 얻는 행렬을 의미 $A^T$ 로 표현

In [94]:
print(data2)
data2 = data2.T
print(data2)


tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)


### numpy와 pytorch

- Pytorch는 numpy의 ndarray를 GPU에서 실행시킬 수 있도록 개발되었으므르,
- Pytorch의 tensor와 numpy의 ndarray는 서로 변환 가능
- 이를 위해 Pytorch에서 다음 메서드를 제공
    - 텐서객체.numpy(): tensor 객체를 numpy ndarray 객체로 변환
    - torch.from_numpy(ndarray) : numpy의 ndarray를 tensor 객체로 반환

In [ ]:
import numpy as np

data1 = np.array([[1,2],[3,4]])
print(data1, type(data1))

data2 = torch.from_numpy(data1) # ndarray -> Tensor
print(data2, type(data2))

data3 = data2.numpy() # Tensor -> ndarray
print(data3, type(data3))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


**arange() : 1차원 tensor 생성**

- torch.arange(start, stop, step)

In [100]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [101]:
torch.arange(1,5)

tensor([1, 2, 3, 4])

In [102]:
torch.arange(1,5,2)

tensor([1, 3])

**linspace() : 범위 내 1차원 tensor 균등 생성**
- torch.linspace(start, stop, count)

In [104]:
torch.linspace(1,5,10)

tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])

**tensor 연산**

- 본래 행렬 곱셈은 앞 행렬의 열의 갯수와 뒷 행렬의 행의 갯수가 같아야 행렬의 곱셈이 가능하지만,
- tensor 연산은 shape가 동일해야 하고, 행과 열이 같은 값끼리 연산이 됨

In [ ]:
import torch

data1 = torch.randn(3, 2)
data2 = torch.randn(2, 3)

# data1 * data2  # 오류 발생: shape 다름

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [111]:
data1 = torch.full((2,2),2)
data2 = torch.full((2,2),3)
data1 * data2

tensor([[6, 6],
        [6, 6]])

In [112]:
data1 = torch.full((3,3),2)
data2 = torch.full((3,3),1)

print(data1 + data2)
print(data1 - data2)
print(data1 * data2)
print(data1 / data2)


tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [113]:
data1 = torch.full((3,2),2)
data2 = torch.full((2,3),1)
torch.matmul(data1,data2)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

In [114]:
print(data1 * data2)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

**Tensor연산 (브로드캐스팅)**
- Tensor 간 연산이 broadcasting을 지원하며, Tensor는 동일한 차원으로 자동 확장됨

**broadcasting 이해**
- 둘 tensor 중 하나의 차원의 원소 수가 1이거나, 존재하지 않을 경우, broadcasting이 일어나면, 해당 차원이 확대됨

In [117]:
data1 = torch.FloatTensor([[1],[2],[3]])
data2 = torch.FloatTensor([1,1,1])
data3 = data1 + data2

print(data1.shape, data2.shape, data3.shape)
print(data3)

torch.Size([3, 1]) torch.Size([3]) torch.Size([3, 3])
tensor([[2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])


**broadcasting 조건**
- 두 tensor 간의 브로드캐스팅이 가능하기 위한 조건이 있음
    - 두 tensor에 있는 각 차원에 대해, 끝쪽 차원부터 다음 조건을 비교하며, 앞쪽 방향으로 진행
        - 각 차원의 원소 수가 똑같거나
        - 둘 중의 하나의 차원의 원소 수는 1이거나, 존재하지 않을 경우

- 주요 브로드캐스팅 기능 케이스를 broadcastable 이라고 함

In [120]:
data1 = torch.FloatTensor(10,20,4)
data2 = torch.FloatTensor(20,4)
data3 = data1 + data2
print(data1.shape, data2.shape, data3.shape)

torch.Size([10, 20, 4]) torch.Size([20, 4]) torch.Size([10, 20, 4])


In [121]:
data1 = torch.FloatTensor(10,1,5)
data2 = torch.FloatTensor(10,2,1)
data3 = data1 + data2
print(data1.shape, data2.shape, data3.shape)

torch.Size([10, 1, 5]) torch.Size([10, 2, 1]) torch.Size([10, 2, 5])


In [122]:
data1 = torch.FloatTensor(5)
data2 = torch.FloatTensor(10,10,1)
data3 = data1 + data2
print(data1.shape, data2.shape, data3.shape)

torch.Size([5]) torch.Size([10, 10, 1]) torch.Size([10, 10, 5])


**tensor의 원소 접근 방법 (indexing)**
- tensor의 특정 데이터를 가져오는 기능 indexing이라고 함

In [ ]:
data3 = torch.FloatTensor([[1.,2.,3.],[4.,5.,6.]])
print(data3)
print(data3[1,1])
print(data3[:,1]) # 슬라이싱, : 는 전체를 의미
print(data3[:,:])
print(data3[:1,:2]) # 슬라이싱, :1 이란 1 - 1인 0까지를 의미하므로, 

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(5.)
tensor([2., 5.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.]])


**boolean indexing**
- 조건 필터링과 검색을 동시에 할 수 있어서, 유용하게 쓰이는 인덱스 기법

In [133]:
data1 = torch.FloatTensor([[1,2,3],[5,5,5]])
data2 = data1 > 3

print(data2)
print(data1[data2])
print(data1[(data1 > 3) & (data1 < 5)])

tensor([[False, False, False],
        [ True,  True,  True]])
tensor([5., 5., 5.])
tensor([])


**fancy indexing**
- 다른 배열로 배열을 인덱싱할 수 있는 기능
- 이를 통해, 복잡한 배열의 연속되지 않은 일부분을 빠르게 접근할 수 있음

In [134]:
data1 = torch.randn(4,3)
data1

tensor([[ 0.1797, -1.0917, -1.2264],
        [ 1.9119,  1.9330, -0.7321],
        [-1.7298,  0.4356,  1.4910],
        [-0.3745,  0.0413,  1.3064]])

In [137]:
# 특정 행 배열 추출하기

print(data1[[1,2,0]])
print(data1[[1,-1]])

tensor([[ 1.9119,  1.9330, -0.7321],
        [-1.7298,  0.4356,  1.4910],
        [ 0.1797, -1.0917, -1.2264]])
tensor([[ 1.9119,  1.9330, -0.7321],
        [-0.3745,  0.0413,  1.3064]])


In [143]:
print(data1[[1,2]][:,[0,2]]) # 1,2 행을 선택하고 전체 행을 선택한 후 이 중에 0번째 열과 2번째 열만 추출하기
print(data1[[1,-1]][:,[0]]) # 1,2 행을 선택하고 전체 행을 선택한 후 이 중에 0번째 열과 2번째 열만 추출하기

tensor([[ 1.9119, -0.7321],
        [-1.7298,  1.4910]])
tensor([[ 1.9119],
        [-0.3745]])


**텐서 복사: 텐서 객체.clone().detach()**
- Pytorch 에서 tensor를 복사하는 다양한 방법이 존재하지만,
- 이 중에서, 위 메서드를 사용하는 것이 가장 깔끔한 방법
    - clone() : 기존 텐서객체의 내용을 복사한 텐서 생성
    - detach() : 기존 텐서객체 그래프에서 분리된 텐서를 생성


In [145]:
data1 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(data1)


data2 = data1[:2,:2]
print(data2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])


In [ ]:
data2[1,1] = 4
print(data2)
print(data1) # 얕은 복사

tensor([[1., 2.],
        [4., 4.]])
tensor([[1., 2., 3.],
        [4., 4., 6.]])


In [152]:
data1 = torch.FloatTensor([[1,2,3],[4,5,6]])
print(data1)

data2 = data1[:2,:2].clone().detach() # .clone().detach() 로 복사하면 됨
print(data2)

data2[1,1] = 4
print(data2)
print(data1) # 깊은 복사

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[1., 2.],
        [4., 4.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


**tensor 조건 연산 : where()**
- torch.where(조건 참일 때의 배열, 거짓일 때의 배열)

In [155]:
data1 = torch.FloatTensor([7,2,0,4,1])
index = torch.where(data1 < 3) # 조건에 맞는 인덱스 번호 생성
print(index)
print(data1[index])

(tensor([1, 2, 4]),)
tensor([2., 0., 1.])


**조건에 맞는 값 특정 다른 값으로 변환**

In [158]:
print(data1)
data2 = torch.where(data1 < 3, -1, 1) # 조건에 맞으면 -1 틀리면 1으로 원소 값을 수정
print(data2)

tensor([7., 2., 0., 4., 1.])
tensor([ 1, -1, -1,  1, -1])


**다차원 배열에도 적용 가능**

In [159]:
data1 = torch.FloatTensor([[1,2,3],[4,5,6]])
data2 = torch.where(data1 < 3, -1, 1)
print(data2)

tensor([[-1, -1,  1],
        [ 1,  1,  1]])


**tensor 데이터 분석**
- min(), max(), sum(), mean(), var(), std() : 최대값,최소값,합계값,평균값,분산값,표준편차값
- argmin(), argmax() : 최소값의 인덱스 번호, 최대값의 인덱스 번호

In [160]:
data1 = torch.FloatTensor([[1,2,3],[4,5,6]])

print(data1.min())
print(data1.max())
print(data1.sum())
print(data1.mean())
print(data1.var())
print(data1.std())
print(data1.argmin())
print(data1.argmax())

tensor(1.)
tensor(6.)
tensor(21.)
tensor(3.5000)
tensor(3.5000)
tensor(1.8708)
tensor(0)
tensor(5)


**텐서를 파일로 저장하고 불러오기**

- 한 개의 텐서 저장
    - save()로 파일 저장 가능

In [163]:
data1 = torch.linspace(1,5,4)
print(data1)
torch.save(data1,"mydata1.pt")

tensor([1.0000, 2.3333, 3.6667, 5.0000])


**한 개의 텐서 읽어오기**
- load()로 파일로 저장된 1차원 배열을 읽어올 수 있음

In [164]:
data2 = torch.load('mydata1.pt')
print(data2)

tensor([1.0000, 2.3333, 3.6667, 5.0000])


**한 개 이상의 텐서 저장**
- 각 배열을 key=배열 로 key 값을 지정할 수 있음

In [ ]:
data1 = torch.linspace(1,5,4)
data2 = torch.linspace(1,10,4)
data3 = torch.linspace(1,100,4)
print(data1)
print(data2)
print(data3)

datas = {'data1':data1,'data2':data2,'data3':data3}
torch.save(datas,'mydata1.pt')

tensor([1.0000, 2.3333, 3.6667, 5.0000])
tensor([ 1.,  4.,  7., 10.])
tensor([  1.,  34.,  67., 100.])


In [172]:
datas = torch.load('mydata1.pt')
print(datas)
print(datas['data1'])
print(datas['data2'])
print(datas['data3'])

{'data1': tensor([1.0000, 2.3333, 3.6667, 5.0000]), 'data2': tensor([ 1.,  4.,  7., 10.]), 'data3': tensor([  1.,  34.,  67., 100.])}
tensor([1.0000, 2.3333, 3.6667, 5.0000])
tensor([ 1.,  4.,  7., 10.])
tensor([  1.,  34.,  67., 100.])


In [170]:
print(type(datas))

<class 'dict'>
