### 텐서간 곱셈 정리와 관련 메서드 익히기

### PyTorch와 텐서간의 곱셈

- torch.matmal() : 메서드가 다양한 텐서 곱셈 연산을 지원
- torch.mm()은 2D 텐서, torch.bmm()은 3D 텐서 간의 연산만 지원합니다.

> 그래서 matmal() 메서드와의 차이점을 알 필요가 있다.

In [2]:
import torch

A = torch.full((3,),2) # vector 생성
B = torch.full((3,),3)

print(A, A.dim(), A.shape)
print(B, B.dim(), B.shape)
result = torch.matmul(A,B)
print(result, result.shape) # scala 값이 반환됩니다.

tensor([2, 2, 2]) 1 torch.Size([3])
tensor([3, 3, 3]) 1 torch.Size([3])
tensor(18) torch.Size([])


In [5]:
A = torch.full((3,2),2)
B = torch.full((2,3),3)

result = torch.matmul(A,B)

print(result.shape)


torch.Size([3, 3])


**1D(벡터) X 2D(행렬)**

In [6]:
x = torch.full((3,),2)
A = torch.full((3,2),3)

result = torch.matmul(x,A)
print(result, result.shape)

tensor([18, 18]) torch.Size([2])


**2D(행렬) X 1D(벡터)**

In [7]:
import torch

x = torch.full((2,),2)
A = torch.full((3,2),3)

result = torch.matmul(A,x)

print(result, result.shape)

tensor([12, 12, 12]) torch.Size([3])


**3D 이상 텐서 X 1D 텐서 (벡터)**

In [8]:
import torch

x = torch.full((2,),2)
A = torch.full((4,3,2),3)

result = torch.matmul(A,x)
print(result, result.shape)

tensor([[12, 12, 12],
        [12, 12, 12],
        [12, 12, 12],
        [12, 12, 12]]) torch.Size([4, 3])


In [10]:
import torch


data1 = torch.full((10,1,3,4),2)
data2 = torch.full((2,4,5),3)

print(data1.dim(), data1.shape)
print(data2.dim(), data2.shape)

data3 = torch.matmul(data1, data2)
print(data3.shape)

4 torch.Size([10, 1, 3, 4])
3 torch.Size([2, 4, 5])
torch.Size([10, 2, 3, 5])


In [11]:
import torch


data1 = torch.full((10,8,3,4),2)
data2 = torch.full((1,8,4,5),3)

print(data1.dim(), data1.shape)
print(data2.dim(), data2.shape)

data3 = torch.matmul(data1, data2)
print(data3.shape)

4 torch.Size([10, 8, 3, 4])
4 torch.Size([1, 8, 4, 5])
torch.Size([10, 8, 3, 5])


**torch.mm()**

- 행렬곱만 지원함

- 두 인자 모두 행렬 shape 이어야 함

In [ ]:
import torch

data1 = torch.full((3,4),2)
data2 = torch.full((4,5),3)

print(data1.dim(), data1.shape) # 2, (3, 4)

print(data2.dim(), data2.shape) # 2 , (4, 5)

data3 = torch.mm(data1,data2)
print(data3.shape) # (3, 5)

2 torch.Size([3, 4])
2 torch.Size([4, 5])
torch.Size([3, 5])


**torch.bmm()**

- 두 인자 모두 3D 텐서 shape 이어야 함
- boardcast를 지원하지 않으므로, 마지막 두 axis 외에는 두 인자 모두 동일한 차원이어야 함

In [ ]:
import torch

data1 = torch.full((3, 3, 4),2)
data2 = torch.full((3, 4, 5),3)

print(data1.dim(), data1.shape)

print(data2.dim(), data2.shape)

data3 = torch.bmm(data1,data2)
print(data3.shape) 

3 torch.Size([3, 3, 4])
3 torch.Size([3, 4, 5])
torch.Size([3, 3, 5])
