### Pytorch 모델 용어 정리 

- 계층 (layer) : 모듈 또는 모듈을 구성하는 한 개의 계층을 의미함 (예 : 선형 계층, Linear Layer)

- 모듈 (module) : 한 개 이상의 계층이 모여 구성된 것, 모듈이 모여서 새로운 모듈 구성 가능

- 모델 (model) : 최종적인 네트워크 한 개의 모듈이 모델이 될 수도 있고, 여러 개의 모듈이 하나의 모델이 될 수 있음

### torch.nn과 nn.Module

- torch.nn 네임스페이스는 신경망을 구성하는데 필요한 모든 구성 요소 제공

- 모든 PyTorch 모듈은 nn.Module의 하위 클래스(subclass) 임

- 모든 PyTorch 신경망 모델은 nn.Module 을 상속받은 하위 클래스로 정의함
    - __init__에서 신경망 계층 초기화 필요
    - forward() 메서드에서 입력 데이터에 대한 연산 정의 필요

### Raw-level Linear Layer 구현

- Linear Layer 이론, 수학적 이해, 실제 PyTorch의 필요 문법까지 익혔으므로,
- 이를 기반으로 Linear Layer의 보다 선명한 이해 및 PyTorch에 익숙해지기 위해, Linear Layer를 가볍게 구현해보기로 함
- 입력 차원이 4, 출력 차원이 3이고, Linear Layer 함수를 $f(x) = x * W + b$ 이라고 하면,
- 다음과 같은 방식으로 계산되므로,

In [25]:
import torch

x = torch.FloatTensor(4) # 입력
W = torch.FloatTensor(4, 3) # 가중치
b = torch.FloatTensor(3) # 편향

In [26]:
import torch

def linearfunction(x, W, b) :
    y = torch.matmul(x, W) + b
    return y

In [27]:
print("W", W.shape, "x", x.shape, "b", b.shape)

W torch.Size([4, 3]) x torch.Size([4]) b torch.Size([3])


In [28]:
y = linearfunction(x, W, b)
print(y.shape)

torch.Size([3])


### nn.Module 기반, Linear Layer 구현

- 신경망 모델 클래스를 만들고, nn.Module 을 상속받음

- __init__에서 신경망 계층 초기화 선언

- forward() 메서드에서 입력 데이터에 대한 연산 정의


In [47]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module) :
    def __init__(self) :
        super().__init__()
        # __init__() 에서 신경망 계층 초기화
        self.W = torch.FloatTensor(4,3)
        self.b = torch.FloatTensor(3)
    
    def forward(self, x) :
        y = torch.matmul(x, self.W) + self.b
        return y

In [48]:
x = torch.FloatTensor(4)

y = NeuralNetwork().forward(x)

In [31]:
print(y, y.shape)

tensor([0., 0., 0.]) torch.Size([3])


In [32]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module) :
    def __init__(self, input_dim, output_dim) :
        super().__init__()
        # __init__() 에서 신경망 계층 초기화
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)
    
    def forward(self, x) :
        y = torch.matmul(x, self.W) + self.b
        return y

In [36]:
x = torch.FloatTensor(4)

mylinear = NeuralNetwork(4, 3)

y = mylinear(x)

print(y, y.shape)

tensor([0., 0., 0.]) torch.Size([3])


In [38]:
for param in mylinear.parameters() :
    print(param)

In [44]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module) :
    def __init__(self, input_dim, output_dim) :
        super().__init__()
        # __init__() 에서 신경망 계층 초기화
        self.W = nn.Parameter(torch.randn(input_dim, output_dim))
        self.b = nn.Parameter(torch.randn(output_dim))
    
    def forward(self, x) :
        y = torch.matmul(x, self.W) + self.b
        return y

In [45]:
x = torch.rand(4)

mylinear = NeuralNetwork(4, 3)

y = mylinear(x)

print(y, y.shape)

for param in mylinear.parameters() :
    print(param)

tensor([-0.3569,  0.5765,  1.2102], grad_fn=<AddBackward0>) torch.Size([3])
Parameter containing:
tensor([[-1.8934,  0.6345, -0.7989],
        [ 0.9339, -0.1070, -1.8543],
        [ 0.8778, -0.8969,  1.1414],
        [-1.5152,  1.0693, -0.5273]], requires_grad=True)
Parameter containing:
tensor([0.3424, 0.4442, 0.9453], requires_grad=True)


### nn.Linear 클래스

- 지금까지는 Linear Layer와 PyTorch 기반 신경망 모듈 구현 방법을 이해하기 위해, Linear Layer를 PyTorch 의 신경망 모듈 클래스로 구현해 본 것 입니다.

In [49]:
mylinear = nn.Linear(4,3)

y = mylinear(x)

print(y, y.shape)

for param in mylinear.parameters() :
    print(param)

tensor([0.0730, 0.1868, 0.3002], grad_fn=<ViewBackward0>) torch.Size([3])
Parameter containing:
tensor([[-0.0242, -0.3998,  0.4187, -0.0150],
        [ 0.0174, -0.1993,  0.3851, -0.0246],
        [-0.4538,  0.2963,  0.1114, -0.2917]], requires_grad=True)
Parameter containing:
tensor([0.0730, 0.1868, 0.3002], requires_grad=True)


In [50]:
class NeuralNetwork(nn.Module) :
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, output_dim)
    
    def forward(self, x):
        y = self.linear(x)
        return y

In [57]:
x = torch.rand(4)

mylinear = NeuralNetwork(4,3)
y = mylinear(x)

print(y, y.shape)

for param in mylinear.parameters() :
    print(param)

tensor([ 0.0545,  0.0081, -0.3038], grad_fn=<ViewBackward0>) torch.Size([3])
Parameter containing:
tensor([[-0.2729,  0.4072,  0.0237, -0.3517],
        [-0.3447,  0.0361, -0.3354,  0.3082],
        [-0.3892,  0.1648, -0.0117,  0.2945]], requires_grad=True)
Parameter containing:
tensor([ 0.0689,  0.4649, -0.2427], requires_grad=True)
